apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjM05EZ3pNakE1TWl3aWFXRjBJam94TnpjME9ETXlNRGt5ZlEuNHhWcEhwTHZKR0MxQ0NIUWNvM2tBZWNpV0VzWE5FbzUwb1FjU0Vjbm5GZwo=
